### ISSUE TITLE
Make pigar respect gitignore

### ISSUE THREAD

**Issue by ishandutta2007** [damnever/pigar#111]
I have subfolder which I like to ignore as specified in my gitignore.
But there is no way to avoid those for pigar.
Let me know if this is already passible,

**Comment by damnever** [comment]
pigar does not respect gitignore, however, there is already an option to ignore directories:
```
-i DIR [DIR ...]      given a list of directory to ignore, relative directory
```

Feel free to reopen this issue if it does not work.
