### ISSUE TITLE
Providing an error message and creating an empty requirements.txt file

### ISSUE THREAD

**Issue by GG-Delta** [damnever/pigar#112]
Hey there, 
I just installed your tool, but unfortunately I keep running into the following error: when typing the command `pigar` (being within the project folder) I get the following error:
>  12:21:14 parse /Users/user123/Coding/dwork01/ML_Pocket_Reference_M.H.ipynb:1 failed: SyntaxError('invalid syntax', ('<unknown>', 78, 1, '!{sys.executable} -m pip install --upgrade setuptools\n', 78, 2))
Writing requirements to "/Users/user123/Coding/dwork01/requirements.txt"
Requirements file has been overwritten, no difference.

The resulting requirements.txt files is empty except for the following generic comment:
"# Automatically generated by https://github.com/damnever/pigar."

I am using pigar version 1.0.0  and I am running an virtual environment using virtualenvwrapper. I would be very grateful to you if you could point me to any solution or correcting any misunderstanding on my side. 
Thanks a lot & all the best,
Gernot

**Comment by damnever** [comment]
Possible solution: https://github.com/damnever/pigar/pull/102

**Comment by damnever** [comment]
Try the main branch: ```pip install git+https://github.com/damnever/pigar.git@main --upgrade```
