### ISSUE TITLE
pigar may include packages which are not required

### ISSUE THREAD

**Issue by daknuett** [damnever/pigar#123]
I recently found that the package [`pyqcs`](https://github.com/daknuett/PyQCS) has been marked as "used by" by several projects on github. These projects have  `requirements.txt` which are automatically generated using `pigar`. In the code the package is not used. 

Perhaps this is a user error by the maintainers or a bug in `pigar`.

Related repositories are:

- https://github.com/innerfirexy/COLING2022-RationalGestures
- https://github.com/EigerEx/geoMetaDetection
- https://github.com/john-preston-uwimona/sensornet-client

**Comment by damnever** [comment]
`pyqcs` is a dirty record of `yaml`, this will be fixed in next release.

**Comment by damnever** [comment]
pigar v2 `pip install pigar==2.0.0` should fix this issue
