### ISSUE TITLE
Pigar 2.0.2 fails when running on github actions through poetry

### ISSUE THREAD

**Issue by h3llrais3r** [damnever/pigar#134]
I'm running pigar via poetry in a bash shell on windows.
I'm doing the same on my github action to be sure to have the same output as on my local machine.
Running it on my local machine doesn't cause any problems.
However, when running on github actions, it complains that paths are not on the same drive...

Python seems to be available at C drive, while project is available on D drive while running pigar from venv within project folder...

You can check it here: https://github.com/h3llrais3r/Auto-Subliminal/actions/runs/3679534191/jobs/6224099590

![image](https://user-images.githubusercontent.com/1945295/207426813-d830ce92-85a1-45fa-b022-5a134f249643.png)

Command inside the script to run pigar:
 
![image](https://user-images.githubusercontent.com/1945295/207428416-dbb7baf8-d9bb-419c-aea9-4fae986265b7.png)

**Comment by damnever** [comment]
`pip install pigar==2.0.3` may have fixed this issue.

Feel free to reopen this issue.

**Comment by h3llrais3r** [comment]
Thanks will test and provide feedback.

**Comment by h3llrais3r** [comment]
Github actions runs fine now: https://github.com/h3llrais3r/Auto-Subliminal/actions/runs/3702327630/jobs/6272480181
![image](https://user-images.githubusercontent.com/1945295/207814254-937c701e-f173-4da3-ae34-6c7f07434fa4.png)

Thanks!
