### ISSUE TITLE
Pigar dependencies contradict project dep

### ISSUE THREAD

**Issue by 2minCS** [damnever/pigar#140]
Pigar depends exclusively on Rich 12.5.1 despite it being superseded by 12.6.0. Is 12.5.1 the version needed or can it be updated?

<img width="1239" alt="pip_pigar" src="https://user-images.githubusercontent.com/117036131/209502752-c800c9de-edd1-4894-bbfb-40adb5d47194.PNG">

**Comment by damnever** [comment]
`pip install pigar==2.0.5` has relaxed some requirements, but we need a more elegant method to fix this kind of problem.

**Comment by damnever** [comment]
The latest version of pigar(`pip install pigar==2.0.6`), has minimal requirements. I believe we have done all we can for now.
