### ISSUE TITLE
PyQt5 search not have correct result

### ISSUE THREAD

**Issue by peterzhenghj** [damnever/pigar#143]
> Please select one or more packages from the below list for the module "PyQt5" (input * to select all, multiple values can be sperated by ",")
[pyqt5-sip, python-qt5, soloman, soloman-controls]

the PyPI page link is https://pypi.org/project/PyQt5/

**Comment by damnever** [comment]
Installing it in the local environment may temporarily fix this issue, see https://github.com/damnever/pigar#faq

I will submit a proper fix in the next few days.

**Comment by damnever** [comment]
`pip install pigar==2.0.5` has been released.
