### ISSUE TITLE
pep517 has been replaced by pyproject-hooks

### ISSUE THREAD

**Issue by yochananmarqos** [damnever/pigar#147]
Just an FYI:

> Note: The pep517 project has been replaced by this project (low level) and the build project (high level).

 -- https://github.com/pypa/pyproject-hooks#readme

**Comment by damnever** [comment]
Thanks, the pep517 is required by pip, which is an indirect dependency of pigar.

pip has [vendored the code of pep517](https://github.com/pypa/pip/tree/main/src/pip/_vendor) to avoid cyclic dependency, and pigar is vendoring pip to avoid conflicts and incompatibility changes. Maybe pigar should vendor all the dependencies..

**Comment by damnever** [comment]
I didn't see a new release of pip with the commit included, and I think there is no significant problem if we don't replace pep517 right now, so let's wait.
