### ISSUE TITLE
[FR] Support __import__ and importlib.import_module

### ISSUE THREAD

**Issue by spacewander** [Damnever/pigar#19]
[`__import__`](https://docs.python.org/2/library/functions.html#__import__)
[`importlib.import_module`](https://docs.python.org/2/library/importlib.html)

Last week I tried pigar on one of my project and it worked as what I wanted.
Pigar is a helpful tool!

Currently pigar can cover more than 99% of requirement. But if it can support `__import__` and `importlib.import_module`, it would be more perfect. Would you consider it?

**Comment by Damnever** [comment]
In most cases, I think people will use it to import module from local project.

Anyway, that's good, would you mind submitting a PR.

And, considering top level package is enough.
