### ISSUE TITLE
Cannot select ... for the module "PyQt6"

### ISSUE THREAD

**Issue by ghbaud** [damnever/pigar#190]
**Describe the bug**
When I do pigar gen for my python project, I get the following message:

```
Please select one or more packages from the below list for the module "PyQt6" (input * to select all, multiple values can be sperated by ",")       
[PyQt6, PyQt6-sip]
(the best match may be "PyQt6"):
```

But when I enter PyQt6 or *, it simply repeats the message. The only way to break out is control C.

**Context (Environment)**
 - OS: Windows 11
 - Version of `Python`: 3.11.3
 - Version of `pigar`: 2.1.1
 - running in vs code Powershell terminal

**Comment by ThetomekK** [comment]
same here

**Comment by kaixxx** [comment]
I have the same problem. A little sad to see this serious issue being unresolved for so long.

**Comment by damnever** [comment]
I'm unable to assist because I can't reproduce this issue on macOS with the latest version of `pigar` installed. It might be related to the Windows environment or character encoding.

**Comment by kaixxx** [comment]
@damnever Thank you. Do you have an idea where to look in the code? I can do some experiments.

**Comment by damnever** [comment]
@kaixxx The entry point is located [here](https://github.com/damnever/pigar/blob/755aed7132fb950bfa8dd0aa5c19a573edc535d3/pigar/__main__.py#L226). This callback is used to prompt the user and retrieve the input. You might need to dig further from here. If you have more specific questions after looking at the code and debugging, please feel free to ask here.

**Comment by liuyixin-louis** [comment]
same here

**Comment by damnever** [comment]
Can't reproduce this issue on Windows 11 with Python 3.13.1.

If you encounter this problem, please provide a minimal reproducible environment, including details such as your terminal implementation, VS Code version, output of `pip freeze`, code examples, etc.

**Comment by BUZZARDGTA** [comment]
I have the same issue, here's the most minimal example I could show you as an example:
```py
from PyQt6.QtWidgets import QApplication, QLabel, QMainWindow
import sys

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Simple PyQt6 Example")
        self.setGeometry(100, 100, 400, 200)
        self.label = QLabel("Hello, PyQt6!", self)
        self.label.setGeometry(100, 80, 200, 40)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
```

Steps to reproduce:
* put this file in an empty folder
* open cmd there and type: `pigar generate`

**Comment by BUZZARDGTA** [comment]
For anyone having this issue, I've found a fix:
* Select the option you need 3 times if it's `*` and 4 times if it's a manual choice ex: `PyQt6` or `PyQt6_sip`. 
* However open up the generated `requierements.txt` file and remove/add the `#` to the line: `WARNING(pigar): some manual fixes are required since pigar has found duplicate requirements for the same import name.`

The reason this bug happens I believe is probably an issue in `click` module, I think @damnever should def uses `input` instead.

**Comment by damnever** [comment]
@BUZZARDGTA Thank you for your feedback and investigation. I agree that the code is messy and requires significant effort to refactor, as much of it was written during my student days. Unfortunately, few seem willing to submit pull requests, even though everyone would appreciate the improvements.


The reason people choose the [click](https://click.palletsprojects.com/) module is that it provides many useful high-level functions and is easy to use. Personally, I like it despite the possibility of bugs. However, that shouldn’t justify removing it and rewriting the functionality that click already provides. Ideally, click should serve as a wrapper for `input` or similar functions. That said, I’m happy to help investigate even if the bugs come with click. Would you mind upgrading the click module to see if that resolves the issue?

**Comment by damnever** [comment]
>  Would you mind upgrading the click module to see if that resolves the issue?

Never mind, I believe I have found and fixed the issue. Please try installing from this branch:

```
pip uninstall pigar
pip install git+https://github.com/damnever/pigar.git@fix/issue190
```

**Comment by BUZZARDGTA** [comment]
Hello, yep this fixed it:)

![image](https://github.com/user-attachments/assets/11f8a027-46c5-4b11-9ce1-f41d47463d1b)

**Comment by damnever** [comment]
The fix is included in the latest release: `pip install 'pigar>=2.1.7'`.

**Comment by aacovski** [comment]
> The fix is included in the latest release: `pip install 'pigar>=2.1.7'`.

I am getting this error with pigar 2.1.7
