### ISSUE TITLE
 TypeError: coercing to Unicode: need string or buffer,

### ISSUE THREAD

**Issue by buriy** [Damnever/pigar#2]
$ pigar 
Traceback (most recent call last):
  File "/usr/local/bin/pigar", line 7, in <module>
    from pigar.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/pigar/__main__.py", line 17, in <module>
    _installed_pkgs = get_installed_pkgs_detail()
  File "/usr/local/lib/python2.7/dist-packages/pigar/reqs.py", line 187, in get_installed_pkgs_detail
    for file in os.listdir(search_path):
TypeError: coercing to Unicode: need string or buffer, NoneType found

My sys.path is the following:
['', '/usr/local/lib/python2.7/dist-packages/Internet_in_a_Box-0.5.10-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/repoze.lru-0.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/backports.lzma-0.0.3-py2.7-linux-x86_64.egg', 
...,
'/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode']
"""

**Comment by Damnever** [comment]
Try this:
```
pip install git+https://github.com/Damnever/pigar.git@issues2 --upgrade
```

By the way, what platform?

**Comment by buriy** [comment]
Ubuntu LTS 14.04

**Comment by buriy** [comment]
This bug is fixed. I'll add other ones tomorrow.
