### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._vendor.chardet' after updating to pip pip 24.1.1

### ISSUE THREAD

**Issue by grosdode** [damnever/pigar#207]
**Describe the bug**
Get error ModuleNotFoundError: No module named 'pip._vendor.chardet' after updating to pip pip 24.1.1

`C:\Users\XXX\OneDrive - XXX\Documents\PythonScripts\SAP_BOM_to_SE>pigar --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Scripts\pigar.exe\__main__.py", line 4, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\__main__.py", line 12, in <module>
    from .log import enable_pretty_logging, logger
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\log.py", line 3, in <module>
    from .helpers import Color
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\helpers.py", line 13, in <module>
    from ._vendor.pip._internal.req.req_file import get_file_content
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_internal\req\__init__.py", line 5, in <module>
    from pigar._vendor.pip._internal.utils.logging import indent_log
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_internal\utils\logging.py", line 29, in <module>
    from pigar._vendor.pip._internal.utils.misc import ensure_dir
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_internal\utils\misc.py", line 43, in <module>
    from pigar._vendor.pip._internal.exceptions import CommandError, ExternallyManagedEnvironment
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_internal\exceptions.py", line 18, in <module>
    from pigar._vendor.pip._vendor.requests.models import Request, Response
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_vendor\requests\__init__.py", line 149, in <module>
    from . import packages, utils
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_vendor\requests\packages.py", line 8, in <module>
    locals()[package] = __import__(vendored_package)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pip._vendor.chardet'`

**To Reproduce**
run any pigar command

**Context (Environment)**
 - OS: Windows
 - Version of `Python`: 3.12.2
 - Version of `pigar`: 
 `pip install pigar --upgrade
Requirement already satisfied: pigar in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (2.1.4)
Requirement already satisfied: click>=8.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from pigar) (8.1.7)
Requirement already satisfied: nbformat>=5.7 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from pigar) (5.10.4)
Requirement already satisfied: aiohttp>=3.9 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from pigar) (3.9.5)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar) (1.9.4)
Requirement already satisfied: colorama in c:\users\XXX\appdata\roaming\python\python312\site-packages (from click>=8.1->pigar) (0.4.6)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->pigar) (2.19.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->pigar) (4.22.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\XXX\appdata\roaming\python\python312\site-packages (from nbformat>=5.7->pigar) (5.3.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->pigar) (5.14.1)`

**Comment by damnever** [comment]
Yes, this will be released soon, but I cannot give a concrete date. You can install pigar directly from GitHub:
```
pip uninstall pigar
pip install git+https://github.com/damnever/pigar.git@main --upgrade
```

**Comment by grosdode** [comment]
Hi,
thank you for the fast response. After I did the upgrade direkt form GitHub I got:

```
pip uninstall pigar
Found existing installation: pigar 2.1.4
Uninstalling pigar-2.1.4:
  Would remove:
    c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages\pigar-2.1.4.dist-info\*
    c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages\pigar\*
    c:\users\XXX\appdata\local\programs\python\python312\scripts\pigar.exe
Proceed (Y/n)? y
  Successfully uninstalled pigar-2.1.4
```

```
pip install git+https://github.com/damnever/pigar.git@main --upgrade
Collecting git+https://github.com/damnever/pigar.git@main
  Cloning https://github.com/damnever/pigar.git (to revision main) to c:\users\XXX\appdata\local\temp\pip-req-build-612yzf3y
  Running command git clone --filter=blob:none --quiet https://github.com/damnever/pigar.git 'C:\Users\XXX\AppData\Local\Temp\pip-req-build-612yzf3y'
  Resolved https://github.com/damnever/pigar.git to commit 1ae3458d3ed1cc0025d7c3308903a447feff5bfc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: click>=8.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from pigar==2.1.4) (8.1.7)
Requirement already satisfied: nbformat>=5.7 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from pigar==2.1.4) (5.10.4)
Requirement already satisfied: aiohttp>=3.9 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from pigar==2.1.4) (3.9.5)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar==2.1.4) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar==2.1.4) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar==2.1.4) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar==2.1.4) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from aiohttp>=3.9->pigar==2.1.4) (1.9.4)
Requirement already satisfied: colorama in c:\users\XXX\appdata\roaming\python\python312\site-packages (from click>=8.1->pigar==2.1.4) (0.4.6)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->pigar==2.1.4) (2.19.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->pigar==2.1.4) (4.22.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\XXX\appdata\roaming\python\python312\site-packages (from nbformat>=5.7->pigar==2.1.4) (5.3.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->pigar==2.1.4) (5.14.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->pigar==2.1.4) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->pigar==2.1.4) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->pigar==2.1.4) (0.18.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\XXX\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=5.7->pigar==2.1.4) (3.11.0)
Requirement already satisfied: pywin32>=300 in c:\users\XXX\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=5.7->pigar==2.1.4) (306)
Requirement already satisfied: idna>=2.0 in c:\users\XXX\appdata\local\programs\python\python312\lib\site-packages (from yarl<2.0,>=1.0->aiohttp>=3.9->pigar==2.1.4) (3.4)
Building wheels for collected packages: pigar
  Building wheel for pigar (pyproject.toml) ... done
  Created wheel for pigar: filename=pigar-2.1.4-py3-none-any.whl size=26052814 sha256=a81fc012bd43f6a95bcb2a8039ce75bb6882d80a3804edb0892ce1fff9e7b4bb
  Stored in directory: C:\Users\XXX\AppData\Local\Temp\pip-ephem-wheel-cache-na4r1i9v\wheels\d8\16\8e\19d420270d0f8c3a7ec4a283e1a7274c3ab1d2e81855ae5eab
Successfully built pigar
Installing collected packages: pigar
Successfully installed pigar-2.1.4
```

```
pigar -V
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Scripts\pigar.exe\__main__.py", line 4, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\__main__.py", line 12, in <module>
    from .log import enable_pretty_logging, logger
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\log.py", line 3, in <module>
    from .helpers import Color
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\helpers.py", line 15, in <module>
    from ._vendor.pip._internal.network.session import PipSession
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_internal\network\session.py", line 32, in <module>
    from pigar._vendor.pip._vendor import requests, urllib3
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_vendor\requests\__init__.py", line 159, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_vendor\requests\api.py", line 11, in <module>
    from . import sessions
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_vendor\requests\sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pigar\_vendor\pip\_vendor\requests\adapters.py", line 81, in <module>
    _preloaded_ssl_context.load_verify_locations(
FileNotFoundError: [Errno 2] No such file or directory
```

For me, it's not time critical, there are other ways to generate _requirements.txt_ but pigar is a very nice one.

**Comment by damnever** [comment]
The latest commit should have fixed this issue, and I have tested it on a Mac:
```
pip uninstall pigar
pip install git+https://github.com/damnever/pigar.git@main --upgrade
```

**Comment by damnever** [comment]
Try the latest release: `pip install pigar==2.1.6`.

**Comment by grosdode** [comment]
Works for me.
