### ISSUE TITLE
Can not find modules from anaconda

### ISSUE THREAD

**Issue by KDr2** [Damnever/pigar#22]
My python env is an Anaconda installation, and I used several models packaged by anaconda, like `pyyaml`, `tornado`, `flask`, `ipykernel` ...

Pigar can not find them, here's the log:
```
Starting generate requirements ...
The following modules are not found yet:
  yaml referenced from:
    .../models.py: 3
  jupyter_core referenced from:
    .../app.py: 8
  tornado referenced from:
    ....py:...
  ipython_genutils referenced from:
    ....py: 7
  flask referenced from:
    ..../views.py: 1
  ipykernel referenced from:
    .../output.py: 2
  traitlets referenced from:
    ....py: 12,13
    ....py: 6,8
  jupyter_client referenced from:
    ....py: 6,8
    .../__init__.py: 4
```

But modules installed using pip were correctly found by pigar, like `invoke`, `hy`, `jsonschema` ...

**Comment by Damnever** [comment]
Could you find the packages installation path? or post the output of ```python -c "import sys; print(sys.path)"```.

**Comment by KDr2** [comment]
```
$ python
Python 3.5.0 |Anaconda 2.4.0 (x86_64)| (default, Oct 20 2015, 14:39:26)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> for x in sys.path: print(x)
...

/Users/zhuoql/programs/anaconda/lib/python35.zip
/Users/zhuoql/programs/anaconda/lib/python3.5
/Users/zhuoql/programs/anaconda/lib/python3.5/plat-darwin
/Users/zhuoql/programs/anaconda/lib/python3.5/lib-dynload
/Users/zhuoql/programs/anaconda/lib/python3.5/site-packages
/Users/zhuoql/programs/anaconda/lib/python3.5/site-packages/Sphinx-1.3.1-py3.5.egg
/Users/zhuoql/programs/anaconda/lib/python3.5/site-packages/aeosa
/Users/zhuoql/programs/anaconda/lib/python3.5/site-packages/setuptools-18.4-py3.5.egg
>>> import tornado
>>> tornado
<module 'tornado' from '/Users/zhuoql/programs/anaconda/lib/python3.5/site-packages/tornado/__init__.py'>
>>> import invoke
>>> invoke
<module 'invoke' from '/Users/zhuoql/programs/anaconda/lib/python3.5/site-packages/invoke/__init__.py'>
>>>
```

`tornado` and `invoke` are under the same directory, but pigar can only find `invoke`, can not find `tornado`. The only different from them is that: `tornado` is anaconda builtin, `invoke` is installed by pip after installing anaconda.

Thanks.

**Comment by KDr2** [comment]
And also, my PyYAML is installed by pip, but pigar can not find it either.

**Comment by Damnever** [comment]
Does the branch `spkg_missin` works?
`pip install git+https://github.com/Damnever/pigar.git@spkg_missin --upgrade`

**Comment by KDr2** [comment]
Unfortunately nothing is changed, the issue is still there.

Here is the content of my site-packages dir:
http://paste.debian.net/387982/
Hope it will help.

**Comment by Damnever** [comment]
If you want pigar find packages in Anaconda, you need use `path/to/Anaconda/bin/pip install pigar` to install pigar and use `path/to/Anaconda/bin/pigar` to generate requirements file.

The PyYAML problem: I will manual insert the mapping (yaml, PyYAML) to database , therefor pigar can find it on PyPI.
