### ISSUE TITLE
A problem in finding module 'pyprind'

### ISSUE THREAD

**Issue by rhuab** [damnever/pigar#23]
'pyprind' cannot be found by pigar but actually it is a valid module. I tried to use pigar -u to update but pigar tells me the database is not available. Also I tried to use 'pigar -s pyprind' but it told me pyprind is not found.

**Comment by rhuab** [comment]
Also I tried to use pigar -s pyprind but it told me pyprind is not found.

**Comment by Damnever** [comment]
`pip install git+https://github.com/Damnever/pigar.git@master --upgrade`

Need more description about `database is not available`.

**Comment by rhuab** [comment]
Thanks! This command works because pyprind can be found. However, when I use 'pigar -u' to upgrade, it still tells me like this:
Starting update database (this will take a while)...
20:51:03 Extracting "nsot-sync", got: Cannot operate on a closed database.
20:51:12 Crawling "https://pypi.python.org/pypi/sentry-bugzilla/json", got: 404 Not Found
20:51:28 Crawling "https://pypi.python.org/pypi/sff3/json", got: 404 Not Found
20:51:34 Extracting "rfcs", got: Cannot operate on a closed database.
20:51:41 Extracting "sooty", got: Cannot operate on a closed database.
