### ISSUE TITLE
A bug in generating requirements.txt 

### ISSUE THREAD

**Issue by rhuab** [Damnever/pigar#24]
After I use pigar to generate requirements.txt, I find this file contains such a sentence like:
#xxx.py: 10
chardet == 2.3.0.egg
As you can see,  there is a "egg" suffix attached to it which causes an error when I use pip to install
chardet by typing "pip install --user --ignore-installed --no-cache-dir --no-index --find-links=/xxx -r requirements.txt" to install module from local pakage that has been downloaded  according to the requirements.txt.
The error info is like this:
Collecting chardet==2.3.0.egg (from -r /xxx/requirements.txt (line 8))
 Could not find a version that satisfies the requirement chardet==2.3.0.egg (from -r /xxx/requirements.txt (line 8)) (from versions: 2.3.0)
No matching distribution found for chardet==2.3.0.egg (from -r /xxx/requirements.txt (line 8))
but actually I have chardet-2.3.0.tar.gz in path /xxx.
If I type 'pip install --user --ignore-installed --no-cache-dir --no-index --find-links=/xxx chardet', the chardet module will be installed normally.
Therefore, please fix this problem otherwise I cannot download dependencies and pip install them automatically from local packages on another machine under the condition that there is no internet connection.

**Comment by Damnever** [comment]
What is your system?

Try this command in your terminal, and post it:
`ls $(python -c "import sys; print([p for p in sys.path if p.endswith('site-packages')][0])") | grep chardet`

**Comment by rhuab** [comment]
My system is Ubuntu 14. Actually I prefer to write code to modify the problem in requirements.txt so that avoid to use shell command because it will increase the dependence on platform. But this command is quite alright, thanks! By the way, I find another problem in pigar: in my scripts I use WTF plugin of Flask but pigar cannot detect this plugin which should be installed by this command: pip install Flask-WTF, and so on for other plugins of Flask or something like this case. I hope pigar to improve this because I think pigar is really handy and useful and full of potential.

**Comment by Damnever** [comment]
Could you post the output of the shell command, then I can know how to fix the problem.

The another problem which you described is a real problem, I will try to figure it out, thanks.

**Comment by rhuab** [comment]
The error info is like this:
in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.wtf
which should be installed by 'pip install Flask-WTF' but it does not occur in requirements.txt. And so on for Flask-Compress which should be installed by 'pip install Flask-Compress'.

**Comment by Damnever** [comment]
Ok, thanks.

The output of the following command?
```
ls $(python -c "import sys; print(' '.join([p for p in sys.path if p.endswith('site-packages')]))") | grep chardet
```

**Comment by rhuab** [comment]
bson                              pymongo
bson-0.4.2-py2.7.egg-info         pymongo-3.2.1-py2.7.egg-info
chardet                           pyprind
chardet-2.3.0-py2.7.egg-info      PyPrind-2.9.4-py2.7.egg-info
decorator-4.0.6.dist-info         pytz
decorator-4.0.9.dist-info         pytz-2015.7.dist-info
decorator.py                      rdbtools
decorator.pyc                     rdbtools-0.1.6-py2.7.egg-info
flask                             redis
Flask-0.10.1-py2.7.egg-info       redis-2.10.5.dist-info
gridfs                            requests
itsdangerous-0.24-py2.7.egg-info  requests-2.9.1.dist-info
itsdangerous.py                   simplejson
itsdangerous.pyc                  simplejson-3.8.2-py2.7.egg-info
jinja2                            six-1.10.0.dist-info
Jinja2-2.8.dist-info              six.py
markupsafe                        six.pyc
MarkupSafe-0.23-py2.7.egg-info    werkzeug
networkx                          Werkzeug-0.11.4.dist-info
networkx-1.11.dist-info           wtforms
pip                               WTForms-2.1-py2.7.egg-info
pip-8.0.2.dist-info

**Comment by Damnever** [comment]
If you use pigar -s flask_wtf, pigar can find it.

**Comment by rhuab** [comment]
Yes, but it seems weird...

**Comment by Damnever** [comment]
Because you can import Flask-WTF like this: `import flask_wtf`

**Comment by Damnever** [comment]
The chardet problem seems fine in my system, what is your Python version?

**Comment by rhuab** [comment]
Python 2.7.10.
But I think only 'import flask_wtf', then referring to 'flask.ext.wtf' will throw en error. You have to import flask first so that the code 'flask.ext.wtf' works.

**Comment by Damnever** [comment]
In my system(Ubuntu 15.04), Python 2.7.10 also works fine, I do not know where the `.egg` suffix come from...

You can try this:
`python -c "print('chardet-2.3.0-py2.7.egg-info'.split('-')[:2])"`

**Comment by rhuab** [comment]
output: ['chardet', '2.3.0']

**Comment by Damnever** [comment]
flask extension surpported, you can update code from GitHub.
