### ISSUE TITLE
生成的内容自带了很多 .egg

### ISSUE THREAD

**Issue by fy0** [damnever/pigar#28]
vagrant > pigar -v                                                                                                                       16-10-02 20:48 pigar 0.6.10

Python 3.4.3

\# view/__init__.py: 31
Mako == 1.0.4.egg

**Comment by damnever** [comment]
你用下这个命令 `ls $(python -c "import sys; print(' '.join([p for p in sys.path if p.endswith('site-packages')]))") | grep -i mako` 看看输出的内容

**Comment by fy0** [comment]
抱歉 因为是vagrant的机器，之前几天生产环境正好从3.4换到3.5，就删号重来了。。。
现在看了一眼，这问题不能复现了
