### ISSUE TITLE
Pigar does not find ruamel.yaml module

### ISSUE THREAD

**Issue by radek-sprta** [damnever/pigar#29]
As the title suggests, pigar does not catch the ruamel.yaml module, instead it looks for the non-existing ruamel module. (Understandably, given the stupid naming of the module).

**Comment by damnever** [comment]
Need more information, I can't reproduce it, such as system, Python version, pigar version, and how do you install `ruaml.yaml`?

**Comment by radek-sprta** [comment]
Ubuntu 17.04
pigar 0.6.10
Python 3.5.3

pigar and ruamel.yaml both installed in virtualenv using pip

**Comment by damnever** [comment]
I submit a workaround for such special cases, but not a radical cure.. #30
