### ISSUE TITLE
Duplicate dependency for forks (arrow vs arrow-fatisar)

### ISSUE THREAD

**Issue by cgthayer** [damnever/pigar#32]
FYI, after running pigar I picked up both arrow and arrow-fatisar in one requirements.txt which caused some issues (cleared up by deleting the duplicate).

**Comment by damnever** [comment]
Pigar may not be possible to distinguish between them..

**Comment by damnever** [comment]
pigar v2 will ask user to choose the right one, try it: `pip install pigar==2.0.0`.
