### ISSUE TITLE
Pigar, while awesome, misses some packages?

### ISSUE THREAD

**Issue by davidbernat** [damnever/pigar#34]
Hello. Firstly, this module is a godsend. Thank you.

I ran pigar in my repository and all but one package was correctly identified. The missing package, python-box (import box), was necessary to load the module. And I know that module is no dependency of any of the packages pigar identified for requirements.txt.

I ran pigar -u to update the package list. Though it did not change the pigar output (or at least add python-box).

What to do?

Thanks again!

**Comment by damnever** [comment]
The latest version should fix it.
