### ISSUE TITLE
PKG_INFO_URL Deprecated

### ISSUE THREAD

**Issue by devspyrosv** [damnever/pigar#39]
[https://pypi.python.org/pypi/](https://pypi.python.org/pypi/) is deprecated and no longer works. 
pigar throws `urllib2.HTTPError: HTTP Error 404: Not Found`

**Comment by damnever** [comment]
Thanks for mention it, I will check out https://pypi.org as soon as I got time.

**Comment by damnever** [comment]
That's a known issue, the others are still working, since some package may be not found from simple list. Close it for now, feel free to reopen it.
