### ISSUE TITLE
pigar -c doesn't handle referenced files or other flags well

### ISSUE THREAD

**Issue by Gerrit-K** [damnever/pigar#48]
Not a big deal, but pigar treats arguments in requirements.txt files as packages. E.g. sometimes you want to split your requirements or allow private package repositories:

`requirements.txt`:
```
pigar == 0.9.0
-r pigar-requirements.txt

--extra-index-url ...
--trusted-host ...
-r private-requirements.txt
```

Pigar will not treat them differently, but search on pypi.org

**Comment by bganglia** [comment]
@damnever I can work on adding split requirements files, but that will still leave private package repositories.

**Comment by damnever** [comment]
@bganglia PRs are appreciated!
