### ISSUE TITLE
Relaxing version constraints

### ISSUE THREAD

**Issue by jakirkham** [damnever/pigar#49]
Appears that `pigar` now has [very tight version constraints on its dependencies]( https://github.com/damnever/pigar/blob/233658e3468c297bb11889d5a71524bc2a086071/setup.py#L27-L28 ). Would it be possible to relax these (i.e. make them lower bounds instead)?

**Comment by RoobixCube** [comment]
Seconding this, it's introducing version management issues when libraries require newer versions of `requests`
