### ISSUE TITLE
PYPI_URL is hardcoded, does not pick up custom pip configuration.

### ISSUE THREAD

**Issue by SelinGungor** [damnever/pigar#52]
The following piece of code can be improved. `PYPI_URL = 'https://pypi.org' `

Pigar can check whether there is a custom pypi configuration exists or not.  If there is not custom url, it can get by default https://pypi.org.

**Comment by damnever** [comment]
The other PyPI mirrors may has different page structures, I don't know if pigar can handle it gracefully.

**Comment by millsks** [comment]
Came across the same thing recently too.  We have internal mirrors because we are behind a firewall to control what packages are installed.  Any workaround or fix for this so that it reads the pip.conf?
