### ISSUE TITLE
Add support for Notebooks

### ISSUE THREAD

**Issue by ablacklama** [damnever/pigar#53]
Please add support for Ipython Notebooks. A lot of data science/machine learning repos are written partially in python files and partially in notebooks. It would be nice to have a flag that could enable the inclusion of notebooks.

**Comment by damnever** [comment]
Did you mean handling .ipynb as python scripts?

**Comment by ablacklama** [comment]
exactly

**Comment by damnever** [comment]
I do not think it is a good idea.

Maybe [`this`](https://www.google.com/search?newwindow=1&q=install+python+package+within+ipython+notebook) will meet you need. Using containers like docker would be a good idea too.

**Comment by ablacklama** [comment]
maybe  there is a miscommunication or maybe not, but to clarify. I think it would be nice if you could add a flag for .ipynb.
`pegar --include_notebooks=True`
this would mean that pegar would add the imports from notebook files to the requirements.txt that it generates as if they were normal .py files. 

If you think it's a bad idea, that's fine, i just wanted to clarify encase i miscommunicated.

**Comment by damnever** [comment]
I think this kind of job could be done by a pigar plugin or something similar. For now, I want to keep pigar as simple as possible, since I rarely use pigar. Even though, contributions are welcome!

**Comment by damnever** [comment]
Anyway, Jupyter notebook(`.ipynb`) has been [supported](https://pypi.org/project/pigar/). 😅
