### ISSUE TITLE
[Bug] pigar doesn't check if the dev dir is part of a bigger git repository.

### ISSUE THREAD

**Issue by OlivierDehaene** [damnever/pigar#60]
In `reqs.py:_search_path`

```
def _search_path(path):
    mapping = dict()

    for file in os.listdir(path):
        # Install from PYPI.
        if fnmatch.fnmatch(file, '*-info'):
            ...

        # Install from local and available in GitHub.
        elif fnmatch.fnmatch(file, '*-link'):
            ...

            # Check .git dir.
            git_path = os.path.join(dev_dir, '.git')
            ...
            
    return mapping
```

The git directory checking is sufficient for the best case scenario where the package's code is next to the `.git` directory. However if your package is part of a bigger git repository, the checking fails because `git_path` doesn't exist.

One of the potential way of solving this issue would be to write a similar logic to what `pip` does, a subprocess call to `git rev-parse --git-dir`. See: [this line](https://github.com/pypa/pip/blob/master/src/pip/_internal/vcs/git.py#L319). 

If adding `pip` to the dependencies is not an issue, using `pip._internal.vcs.git.Git` directly for the full git logic could be another option.

**Comment by damnever** [comment]
Thanks for reporting this!

You are welcome to submit a PR to address the issue.
