### ISSUE TITLE
Missing modules: follow symlinks & displaying module sources

### ISSUE THREAD

**Issue by buriy** [Damnever/pigar#7]
$ pigar
    Is there modules "feedparser, yadis, yql, js_function_slimmer, apps, keyvalue, kvtool,
    django, queue, django_mailbox, opster, newsdbtables, pyreadline, templateshortcuts,
    flup, goose, oauth2, newsdb, containers" come from other Python
    version(i.e. Python 3) or extension[y/n]? n
    "yadis, js_function_slimmer, opster, newsdbtables, templateshortcuts,
    keyvalue, kvtool, newsdb, containers" not found.
    Maybe you need update database.

Some of the packages listed above were using symlinks.
e.g. "keyvalue" or "containers" are just links.
So they can be considered a part of the main package because they don't have their own setup.py .
>"yadis, js_function_slimmer, opster" not found.

For other modules program output is correct -- they are not found.
Then it would be cool if you could output where they are referenced from -- because sometimes it's a piece of outdated code that needs to be removed or corrected
Like this:

    Not found modules:
    yadis , referenced from myproject/app/tools.py:41
    ...

**Comment by Damnever** [comment]
Good idea, thanks.
