### ISSUE TITLE
Add flag for silent execution

### ISSUE THREAD

**Issue by Metareflektor** [damnever/pigar#76]
The package is very useful and works better than existing alternatives like pipreqs. However, an option for silent execution (without user interaction) would be very useful. For example, a flag regarding the question about PyPi.

**Comment by damnever** [comment]
I think that is a good idea, an option like `-y`/`--assumeyes` to answer yes for all questions is useful.

**Comment by paulbrandkvernelandmechatronics** [comment]
Yes, I am also looking for a flag like this. "echo "n" | pigar ...." does not seem to work on linux OS
