### ISSUE TITLE
pigar unable to recognize html5lib

### ISSUE THREAD

**Issue by Shravan-1908** [damnever/pigar#84]
So this is the code snippet I was working with:
```
from bs4 import BeautifulSoup
import requests

r = requests.get("some-url")
soup =BeautifulSoup(r.content, "html5lib")
...
```

When I later generated requriements.txt with pigar, bs4 and requests were there, but not the parser **html5lib**.

**Comment by damnever** [comment]
You can import it explicitly to resolve this issue.

I don't see a good and simple solution for this, since analyzing the dependencies of dependencies is complicated and we can not execute users' program safely to do some magical things.

**Comment by damnever** [comment]
I recommend you try some package management tools, pigar isn't one.
