### ISSUE TITLE
Sort files in _search_path

### ISSUE THREAD

**Issue by vishalsrao** [damnever/pigar#95]
It may be better if files are read in sorted order in [_search_path](https://github.com/damnever/pigar/blob/2a4f66c4a8125ffa30d5e11d1a0945b511ed1f79/pigar/parser.py#L273). This could help get the latest version when there are multiple versions of the same library.

Change:
`for file in os.listdir(path)`
to
`for file in sorted(os.listdir(path))`

**Comment by damnever** [comment]
The v2 has changed lots of code, feel free to open another issue.
